# Generated by Django 4.2 on 2026-05-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('locked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_locks',
            },
        ),
    ]
