# Generated by Django 4.2 on 2026-05-22 22:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageWindow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('total_units', models.PositiveIntegerField()),
                ('finalized', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_windows', to='customers.customer')),
            ],
            options={
                'db_table': 'usage_windows',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('units', models.PositiveIntegerField()),
                ('event_timestamp', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='customers.apikey')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='customers.customer')),
            ],
            options={
                'db_table': 'usage_events',
            },
        ),
        migrations.AddIndex(
            model_name='usagewindow',
            index=models.Index(fields=['customer', 'window_start'], name='usage_windo_custome_773f23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagewindow',
            unique_together={('customer', 'window_start')},
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['customer', 'event_timestamp'], name='usage_event_custome_f37f3a_idx'),
        ),
    ]
